//! Scientific and format boundaries for exact native IR and legacy expressions.
use fastsecdec::{
    Atom,
    generation::{GenerationOptions, generate},
    kernel::{KernelSet, PrecisionPolicy},
    parametric::{
        FactorRole, ParametricDomain, ParametricIntegrand, ParametricTerm, PolynomialFactor,
    },
};
use std::ops::ControlFlow;
use symbolica::{parse, symbol};

#[path = "inspection_metadata/mod.rs"]
mod inspection_metadata;
#[path = "kernel_artifacts/literal_zero.rs"]
mod literal_zero;

fn generated() -> fastsecdec::generation::GeneratedIntegral {
    generate(
        &ParametricIntegrand::new(
            vec![symbol!("artifact_v3::x")],
            symbol!("artifact_v3::eps"),
            ParametricDomain::UnitCube,
            vec![ParametricTerm::new(
                parse!("(2+3𝑖)*gamma(1+artifact_v3::eps)"),
                vec![Atom::Zero],
                vec![PolynomialFactor::new(
                    parse!("1+artifact_v3::x"),
                    parse!("artifact_v3::eps-1"),
                    FactorRole::Singularity,
                )],
            )],
        )
        .unwrap(),
        &GenerationOptions {
            max_order: 2,
            ..Default::default()
        },
        |_| ControlFlow::Continue(()),
    )
    .unwrap()
}

#[cfg(feature = "native")]
#[test]
fn legacy_v1_v2_keep_original_identity_bytes_and_expression_semantics() {
    // Captured from the validated pre-v3 triangle artifact, not generated by the
    // new serializer. Its native source expressions and semantic metadata remain.
    let v2 = include_bytes!("fixtures/kernel-v2-triangle.json").as_slice();
    let original: serde_json::Value = serde_json::from_slice(v2).unwrap();
    let v1 = include_bytes!("fixtures/kernel-v1-triangle.json").as_slice();
    for (bytes, has_metadata) in [(v2, true), (v1, false)] {
        let mut kernel = KernelSet::from_bytes(bytes).unwrap();
        assert_eq!(kernel.generation_metadata().is_some(), has_metadata);
        if has_metadata {
            assert_eq!(
                kernel.content_id(),
                original["content_id"].as_str().unwrap()
            );
        }
        let mut total = kernel.exact_coefficients().to_vec();
        for sector in kernel.sectors_mut() {
            let mut result = vec![0.0; 3];
            sector.evaluate(&[0.25, 0.5], &mut result).unwrap();
            assert!(result.iter().all(|v| v.is_finite()));
            for (sum, value) in total.iter_mut().zip(result) {
                *sum += value;
            }
        }
        assert_eq!(total[0], -1.0);
        assert_eq!(kernel.artifact_bytes().unwrap(), bytes);
        assert_eq!(kernel.to_bytes().unwrap(), bytes);
    }
}

#[test]
fn native_program_is_saved_without_materialization_and_stays_immutable_after_work() {
    let generated = generated();
    let before_compile = generated
        .to_kernel_bytes(PrecisionPolicy::default())
        .unwrap();
    let mut compiled = generated.compile().unwrap();
    let retained_address = compiled.artifact_bytes().unwrap().as_ptr();
    assert_eq!(compiled.artifact_bytes().unwrap(), before_compile);
    assert_eq!(compiled.to_bytes().unwrap(), before_compile);
    assert!(before_compile.starts_with(b"FastSecDec\0binserde\x07"));
    assert!(serde_json::from_slice::<serde_json::Value>(&before_compile).is_err());
    assert!(compiled.sectors()[0].statistics().exact_program_bytes > 0);
    let mut restored = KernelSet::from_bytes(&before_compile).unwrap();
    assert_eq!(restored.orders(), [0, 0, 1, 1, 2, 2]);
    assert_eq!(compiled.content_id(), restored.content_id());
    for point in [0.25, 1e-8] {
        let mut old = vec![0.0; 6];
        let mut new = vec![0.0; 6];
        compiled.sectors_mut()[0]
            .evaluate(&[point], &mut old)
            .unwrap();
        restored.sectors_mut()[0]
            .evaluate(&[point], &mut new)
            .unwrap();
        assert!((new[0] - 2.0 / (1.0 + point)).abs() < 1e-12);
        assert!((new[1] - 3.0 / (1.0 + point)).abs() < 1e-12);
        for (old, new) in old.into_iter().zip(new) {
            assert!((old - new).abs() < 1e-11);
        }
    }
    assert_eq!(restored.to_bytes().unwrap(), before_compile);
    assert_eq!(compiled.to_bytes().unwrap(), before_compile);
    assert_eq!(
        compiled.artifact_bytes().unwrap().as_ptr(),
        retained_address
    );
    assert_eq!(restored.artifact_bytes().unwrap(), before_compile);
}

#[test]
fn binary_transport_retains_owned_and_borrowed_identity() {
    let bytes = generated()
        .to_kernel_bytes(PrecisionPolicy::default())
        .unwrap();
    let restored = KernelSet::from_bytes(&bytes).unwrap();
    assert_eq!(restored.artifact_bytes().unwrap(), bytes);
    let copied = restored.to_bytes().unwrap();
    assert_eq!(copied, bytes);
    assert_ne!(copied.as_ptr(), restored.artifact_bytes().unwrap().as_ptr());
}

#[test]
fn binary_integrity_header_and_exact_byte_exhaustion_are_enforced() {
    let bytes = generated()
        .to_kernel_bytes(PrecisionPolicy::default())
        .unwrap();
    let mut trailing = bytes.clone();
    trailing.push(0);
    let mut corrupt = bytes.clone();
    let last = corrupt.len() - 1;
    corrupt[last] ^= 1;
    let mut unsupported = bytes.clone();
    unsupported[b"FastSecDec\0binserde".len()] = 255;
    for bad in [
        Vec::new(),
        bytes[..bytes.len() - 1].to_vec(),
        trailing,
        corrupt,
        unsupported,
    ] {
        assert!(KernelSet::from_bytes(&bad).is_err());
    }
}

#[cfg(feature = "native")]
#[test]
fn legacy_json_whitespace_is_retained_without_changing_scientific_identity() {
    let bytes = include_bytes!("fixtures/kernel-v2-triangle.json");
    let pretty =
        serde_json::to_vec_pretty(&serde_json::from_slice::<serde_json::Value>(bytes).unwrap())
            .unwrap();
    let original = KernelSet::from_bytes(bytes).unwrap();
    let restored = KernelSet::from_bytes(&pretty).unwrap();
    assert_eq!(original.content_id(), restored.content_id());
    assert_eq!(restored.artifact_bytes().unwrap(), pretty);
}

#[test]
fn configured_optimizer_policy_survives_binary_cold_load() {
    let settings = fastsecdec::kernel::CompilationSettings {
        horner_iterations: 2,
        cpe_rounds: Some(7),
        ..Default::default()
    };
    let original = generated()
        .compile_with_settings_parameters_and_progress(Default::default(), &[], settings, |_| {
            ControlFlow::Continue(())
        })
        .unwrap();
    let bytes = original.artifact_bytes().unwrap();
    let loaded = KernelSet::from_bytes(bytes).unwrap();
    assert_eq!(loaded.compilation_settings(), &settings);
    assert_eq!(loaded.content_id(), original.content_id());
    assert_eq!(loaded.artifact_bytes().unwrap(), bytes);
}

#[cfg(feature = "portable")]
#[test]
fn native_legacy_artifacts_are_rejected_by_the_portable_backend() {
    for bytes in [
        include_bytes!("fixtures/kernel-v1-triangle.json").as_slice(),
        include_bytes!("fixtures/kernel-v2-triangle.json").as_slice(),
    ] {
        let error = match KernelSet::from_bytes(bytes) {
            Ok(_) => panic!("native legacy artifact was accepted"),
            Err(error) => error,
        };
        assert!(
            error.to_string().contains("require the native backend"),
            "{error}"
        );
    }
}
